routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\GenreController;
use App\Http\Controllers\MovieController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');

// Route::group(['middleware' => ['auth']], function () {
// });
Route::group(['middleware' => ['verified'], 'verify' => true], function () {

    Route::prefix('dashboard')->group(function () {
        //admin pages

        Route::get('/', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');
        Route::get('book/{title}', ['as' => 'book.show', 'uses' =>   'BookController@show']);
        Route::resource('roles', RoleController::class);
        Route::resource('users', UserController::class);
        Route::resource('genre', GenreController::class);
        Route::resource('movie', MovieController::class);
    });
});
require __DIR__ . '/auth.php';

app/Models/Movie.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Movie extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'genre',
        'duration',
        'actor_id',
        'sinopsis',
        'poster',
        'trailer',
        'rating',

    ];

    public function setCategoryAttribute($value)
    {
        $this->attributes['genre'] = json_encode($value);
    }

    public function getCategoryAttribute($value)
    {
        return $this->attributes['genre'] = json_decode($value);
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/MovieController.php
<?php

namespace App\Http\Controllers;

use App\Models\Movie;
use App\Models\Genre;
use Illuminate\Http\Request;

class MovieController extends Controller
{


    function __construct()
    {
        $this->middleware('permission:movie-list|movie-create|movie-edit|movie-delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:movie-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:movie-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:movie-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $movies = Movie::latest()->paginate(5);
        return view('dashboard.movie.index', compact('movies'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $genres = Genre::all();
        return view('dashboard.movie.create', compact('genres'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        request()->validate([

            'title' => 'required',
            'genre' => 'required',
            'duration' => 'required',
            'actor_id' => 'required',
            'sinopsis' => 'required',
            'poster' => 'required|image|mimes:jpeg,png,jpg,gif,svg',
            'trailer' => 'required|file|mimetypes:video/mp4',
            'rating' => 'required',

        ]);

        $posterName = time() . '.' . $request->poster->extension();
        $request->poster->move(public_path('images'), $posterName);


        $trailerName = time() . '.' . $request->trailer->extension();
        $request->trailer->move(public_path('videos'), $trailerName);



        $movie = Movie::create([


            'title' => $request->input('title'),
            'genre' => json_encode($request->input('genre')),
            'duration' => $request->input('duration'),
            'actor_id' => $request->input('actor_id'),
            'sinopsis' => $request->input('sinopsis'),
            'poster'       =>  $posterName,
            'trailer' => $trailerName,
            'rating' => $request->input('rating'),
        ]);


        $movie->save();


        return redirect()->route('movie.index')
            ->with('success', 'Movie created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Movie  $movie
     * @return \Illuminate\Http\Response
     */
    public function show(Movie $movie)
    {
        return view('dashboard.movie.show', compact('movie'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Movie  $movie
     * @return \Illuminate\Http\Response
     */
    public function edit(Movie $movie)
    {
        $genres = Genre::all();
        return view('dashboard.movie.edit', compact('movie', 'genres'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Movie  $movie
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Movie $movie)
    {
        request()->validate([
            'title' => 'required',
            'genre_id' => 'required',
            'duration' => 'required',
            'actor_id' => 'required',
            'sinopsis' => 'required',
            'poster' => 'required',
            'trailer' => 'required',
            'rating' => 'required',
        ]);

        $movie->update($request->all());

        return redirect()->route('movie.index')
            ->with('success', 'Product updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Movie  $movie
     * @return \Illuminate\Http\Response
     */
    public function destroy(Movie $movie)
    {
        $movie->delete();

        return redirect()->route('movie.index')
            ->with('success', 'Movie deleted successfully');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/dashboard/movie/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Movie') }}
        </h2>
    </x-slot>



    <div class="row mb-3">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Movie</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('movie.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif


    <form action="{{ route('movie.store') }}" method="POST" enctype="multipart/form-data">
        @csrf


        <div class="row">
            <div class="mb-3">
                <label class="form-label">Title</label>
                <input type="text" name="title" class="form-control">
            </div>
            <div class="mb-3">
                <label for="formFile" class="form-label">Poster</label>
                <input name="poster" class="form-control" type="file" id="formFile">
            </div>
            <div class="mb-3">
                <label for="formFile" class="form-label">Trailer</label>
                <input name="trailer" class="form-control" type="file" id="formFile">
            </div>
            <div class="mb-3">
                <label for="customRange2" class="form-label">Rating</label>
                <input name="rating" type="range" class="form-range" min="0" max="5" id="customRange2">
            </div>

            <div class="mb-3">
                @foreach($genres as $genre)
                <div class="form-check">
                    <input class="form-check-input" name="genre[]" type="checkbox" value="{!! $genre->name !!}"
                        id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                        {{$genre->name}}
                    </label>

                </div>
                @endforeach
            </div>
            <div class="mb-3">
                <label class="form-label">Duration</label>
                <input type="time" name="duration" class="form-control">
            </div>

            <div class="mb-3">
                <label class="form-label">Actor</label>
                <select name="actor_id" class="form-select" aria-label="Default select example">
                    <option selected>Open this select menu</option>
                    <option value="1">Somebody</option>
                    <option value="2">Comedy</option>
                    <option value="3">Three</option>
                </select>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group mb-3">
                    <label class="form-label">Sinopsis</label>
                    <textarea class="form-control" style="height:150px" name="sinopsis" placeholder="Detail"></textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>


    </form>
</x-app-layout>

resources/views/dashboard/movie/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Movie') }}
        </h2>
    </x-slot>



    <div class="row mb-3">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Movie</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('movie.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif


    <form action="{{ route('movie.store') }}" method="POST" enctype="multipart/form-data">
        @csrf


        <div class="row">
            <div class="mb-3">
                <label class="form-label">Title</label>
                <input value="{{ $movie->title }}" type="text" name="title" class="form-control">
            </div>
            <img class="mb-3" style="width: 200px" src="{{asset('images/'.$movie->poster) }}" alt="" srcset="">
            <div class="mb-3">
                <label for="formFile" class="form-label">Poster</label>
                <input name="poster" class="form-control" type="file" id="formFile">
            </div>
            <div class="mb-3">
                <video controls>
                    <source src="{{ asset('videos/'.$movie->trailer) }}" />
                </video>
            </div>
            <div class="mb-3">
                <label for="formFile" class="form-label">Trailer</label>
                <input name="trailer" class="form-control" type="file" id="formFile">
            </div>
            <div class="mb-3">
                <label for="customRange2" class="form-label">Rating</label>
                <input name="rating" type="range" class="form-range" min="0" max="5" id="customRange2">
            </div>

            <div class="mb-3">
                @foreach($genres as $genre)
                <div class="form-check">
                    <input class="form-check-input" name="genre[]" type="checkbox" value="{!! $genre->name !!}"
                        id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                        {{$genre->name}}
                    </label>

                </div>
                @endforeach
            </div>
            <div class="mb-3">
                <label class="form-label">Duration</label>
                <input type="time" name="duration" class="form-control">
            </div>

            <div class="mb-3">
                <label class="form-label">Actor</label>
                <select name="actor_id" class="form-select" aria-label="Default select example">
                    <option selected>Open this select menu</option>
                    <option value="1">Somebody</option>
                    <option value="2">Comedy</option>
                    <option value="3">Three</option>
                </select>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group mb-3">
                    <label class="form-label">Sinopsis</label>
                    <textarea class="form-control" style="height:150px" name="sinopsis" placeholder="Detail"></textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>


    </form>
</x-app-layout>

resources/views/dashboard/movie/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Users') }}
        </h2>
    </x-slot>



    <div class="row mb-3">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                @can('movie-create')
                <a class="btn btn-success" href="{{ route('movie.create') }}"> Create New Movie</a>
                @endcan
            </div>
        </div>
    </div>


    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif


    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Poster</th>
            <th>information</th>

            <th width="280px">Action</th>
        </tr>
        @foreach ($movies as $movie)
        <tr>
            <td style="width: 1px">{{ ++$i }}</td>
            <td style="width: 125px"><img style="width: 125px;object-fit:cover;height:190px;"
                    src="{{ asset('images/'.$movie->poster)  }}" alt="" srcset=""></td>
            <td>
                <h6>
                    <a class="text-decoration-none text-dark" href="{{ route('movie.show',$movie->id) }}">{{
                        $movie->title }}</a>
                </h6>
                @foreach (json_decode($movie->genre) as $genre)
                <a class="text-decoration-none text-muted" href=""> {{ $genre }}</a>
                @endforeach
                <p><i class="bi bi-star-fill"></i> {{ $movie->rating }}</p>

                <p>{{ $movie->sinopsis }}</p>

            </td>

            <td>
                <form action="{{ route('movie.destroy',$movie->id) }}" method="POST">

                    @can('movie-edit')
                    <a class="btn btn-primary" href="{{ route('movie.edit',$movie->id) }}">Edit</a>
                    @endcan


                    @csrf
                    @method('DELETE')
                    @can('movie-delete')
                    <button type="submit" class="btn btn-danger">Delete</button>
                    @endcan
                </form>
            </td>
        </tr>
        @endforeach
    </table>


    {!! $movies->links() !!}
</x-app-layout>

resources/views/dashboard/movie/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>


    <h3>{{ $movie->title }}</h3>
    <p>{{ $movie->duration }}</p>

    <div class="row">
        <div class="col-3">
            <div class="card">
                <img style="height: 467px" src="{{asset('images/'.$movie->poster) }}" alt="" srcset="">
            </div>
        </div>
        <div class="col-9">
            <div class="card">
                <video controls>
                    <source src="{{ asset('videos/'.$movie->trailer) }}" />
                </video>
            </div>
        </div>
    </div>
    </div>



    <div class="row mb-3">
        <div class="col">
            @foreach (json_decode($movie->genre) as $genre)
            <button type="button" class="btn btn-outline-dark mx-1 rounded-pill">{{ $genre }}</button>
            @endforeach
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <p>{{ $movie->sinopsis }}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <h6>Actor {{ $movie->actor_id }}</h6>
        </div>
    </div>


</x-app-layout>