routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\GenreController;
use App\Http\Controllers\MovieController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');

// Route::group(['middleware' => ['auth']], function () {
// });
Route::group(['middleware' => ['verified'], 'verify' => true], function () {

    Route::prefix('dashboard')->group(function () {
        //admin pages

        Route::get('/', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');
        Route::get('book/{title}', ['as' => 'book.show', 'uses' =>   'BookController@show']);
        Route::resource('roles', RoleController::class);
        Route::resource('users', UserController::class);
        Route::resource('genre', GenreController::class);
        Route::resource('movie', MovieController::class);
    });
});
require __DIR__ . '/auth.php';

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Custom CSS -->
    <link href="{{ asset('monster/src/assets/libs/chartist/dist/chartist.min.css') }}" rel="stylesheet">
    <link href="{{ asset('monster/src/assets/extra-libs/c3/c3.min.css') }}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{{ asset('monster/dist/css/style.min.css') }}" rel="stylesheet">
    <link rel="stylesheet"
        href="{{ asset('https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css') }}">

    <!-- Styles -->
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">

    <!-- CSS only -->
    <link href="{{ asset('https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css') }}"
        rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
        crossorigin="anonymous">

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
</head>

<body class="font-sans antialiased">
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <div id="main-wrapper">
        @include('layouts.navigation')
        <div class="page-wrapper">
            <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-md-5 align-self-center">
                        <h5 class="page-title">Dashboard</h5>
                        <div class="d-flex align-items-center">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
                                </ol>
                            </nav>
                        </div>
                    </div>

                </div>
            </div>
            <div class="container-fluid">
                <div class="row">
                    {{ $slot }}
                </div>
            </div>
        </div>


        <!-- Page Content -->


    </div>

    <script src="{{ asset('monster/src/assets/libs/jquery/dist/jquery.min.js') }}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{{ asset('monster/src/assets/libs/popper.js/dist/umd/popper.min.js') }}"></script>
    <script src="{{ asset('monster/src/assets/libs/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <!-- apps -->
    <script src="{{ asset('monster/dist/js/app.min.js') }}"></script>
    <script src="{{ asset('monster/dist/js/app.init.js') }}"></script>
    <script src="{{ asset('monster/dist/js/app-style-switcher.js') }}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="{{ asset('monster/src/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js') }}">
    </script>
    <script src="{{ asset('monster/src/assets/libs/jquery-sparkline/jquery.sparkline.min.js') }}"></script>
    <!--Wave Effects -->
    <script src="{{ asset('monster/dist/js/waves.js') }}"></script>
    <!--Menu sidebar -->
    <script src="{{ asset('monster/dist/js/sidebarmenu.js') }}"></script>
    <!--Custom JavaScript -->
    <script src="{{ asset('monster/dist/js/feather.min.js') }}"></script>
    <script src="{{ asset('monster/dist/js/custom.min.js') }}"></script>
    <!-- This Page Js Files Here -->
    <script src="{{ asset('monster/dist/js/pages/dashboards/dashboard1.js') }}"></script>
</body>

</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <link href="{{ asset('bootstrap/example/assets/dist/css/bootstrap.min.css') }}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }
    </style>

    <!-- Styles -->
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{{ asset('bootstrap/example/blog/blog.css') }}" rel="stylesheet">

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
</head>

<body>
    @include('layouts.userNavigation')
    <div class="font-sans text-gray-900 antialiased">
        <main>
            {{ $slot }}
        </main>
    </div>

    <footer class="blog-footer">
        <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a
                href="https://twitter.com/mdo">@mdo</a>.</p>
        <p>
            <a href="#">Back to top</a>
        </p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous">
    </script>
</body>

</html>

resources/views/layouts/navigation.blade.php
{{-- <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar  collapse">
    <div class="position-sticky pt-3">
        <ul class="nav flex-column">

            <li class="nav-item">
                <a href="{{ route('home') }}" :active="request()->routeIs('home')" class="nav-link active"
                    aria-current="page">
                    <span data-feather="home" class="align-text-bottom"></span>
                    Home
                </a>
            </li>



            <li class="nav-item">
                <a class="nav-link" href="{{ route('dashboard') }}" :active="request()->routeIs('dashboard')">
                    <span data-feather="file" class="align-text-bottom"></span>
                    Dashboard
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ route('users.index') }}" :active="request()->routeIs('users.index')">
                    <span data-feather="shopping-cart" class="align-text-bottom"></span>
                    Manage Users
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ route('movie.index') }}" :active="request()->routeIs('movie.index')">
                    <span data-feather="users" class="align-text-bottom"></span>
                    Manage Movie
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ route('roles.index') }}" :active="request()->routeIs('roles.index')">
                    <span data-feather="bar-chart-2" class="align-text-bottom"></span>
                    Manage Role
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ route('genre.index') }}" :active="request()->routeIs('genre.index')">
                    <span data-feather="bar-chart-2" class="align-text-bottom"></span>
                    Genre
                </a>
            </li>


        </ul>


    </div>
</nav> --}}

<header class="topbar bg-dark">
    <nav class="navbar top-navbar navbar-expand-md navbar-dark ">
        <div class="navbar-header">
            <!-- This is for the sidebar toggle which is visible on mobile only -->
            <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i
                    class="ti-menu ti-close pr-2"></i></a>
            <!-- ============================================================== -->
            <!-- Logo -->
            <!-- ============================================================== -->
            <a class="navbar-brand bg-dark" href="index.html">
                <!-- Logo icon -->
                <b class="logo-icon">
                </b>
                <!--End Logo icon -->
                <!-- Logo text -->
                <span class="logo-text">
                    MovieList
                </span>
            </a>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Toggle which is visible on mobile only -->
            <!-- ============================================================== -->
            <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)"
                data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation"><i class="ti-more pr-2"></i></a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div class="navbar-collapse bg-dark collapse" id="navbarSupportedContent">
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav mr-auto ">
                <li class="nav-item d-none d-md-block"><a class="nav-link sidebartoggler waves-effect waves-light"
                        href="javascript:void(0)" data-sidebartype="mini-sidebar"><i
                            class="icon-arrow-left-circle pr-2"></i></a></li>



            </ul>
            <!-- ============================================================== -->
            <!-- Right side toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav ">
                <!-- ============================================================== -->
                <!-- Search -->
                <!-- ============================================================== -->
                <li class="nav-item search-box d-none d-md-block">
                    <form class="app-search mt-3 mr-2">
                        <input type="text" class="form-control rounded-pill border-0" placeholder="Search for...">
                        <a class="srh-btn"><i class="ti-search pr-2"></i></a>
                    </form>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic" href=""
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i
                            class="bi bi-person-circle text-light fs-3"></i></a>
                    <div class="dropdown-menu dropdown-menu-right user-dd animated flipInY">
                        <div class="d-flex no-block align-items-center p-3 mb-2 border-bottom">
                            <div class=""><img src="../assets/images/users/1.jpg" alt="user" class="rounded" width="80">
                            </div>
                            <div class="ml-2">
                                <h4 class="mb-0">Steave Jobs</h4>
                                <p class=" mb-0">varun@gmail.com</p>
                                <a href="profile.html" class="btn btn-rounded btn-danger btn-sm">View Profile</a>
                            </div>
                        </div>
                        <a class="dropdown-item" href="javascript:void(0)"><i class="ti-user mr-1 ml-1 pr-2"></i> My
                            Profile</a>
                        <a class="dropdown-item" href="javascript:void(0)">
                            <i class="ti-wallet mr-1 ml-1 pr-2"></i> My
                        </a>
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf
                            <a class="dropdown-item" onclick="event.preventDefault();
                                                                            this.closest('form').submit();"
                                href="{{ route('logout') }}">
                                <i class="ti-wallet mr-1 ml-1 pr-2"></i> Logout
                            </a>

                        </form>

                    </div>
                </li>

                <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                    </a>
                    <div class="dropdown-menu dropdown-menu-right  animated bounceInDown"
                        aria-labelledby="navbarDropdown2">

                    </div>
                </div>
            </ul>
        </div>
    </nav>
</header>
<!-- ============================================================== -->
<!-- End Topbar header -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">



                <li class="sidebar-item">
                    <a :active="request()->routeIs('home')"
                        class="sidebar-link text-decoration-none waves-effect waves-dark sidebar-link text-decoration-none"
                        href="{{ route('home') }}" aria-expanded="false">
                        <i class="bi bi-house-door  pr-2"></i>
                        <span class="hide-menu">Home</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a :active="request()->routeIs('dashboard')"
                        class="sidebar-link text-decoration-none waves-effect waves-dark sidebar-link text-decoration-none"
                        href="{{ route('dashboard') }}" aria-expanded="false">
                        <i class="bi bi-speedometer2 pr-2"></i>
                        <span class="hide-menu">Dashboard</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a :active="request()->routeIs('users.index')"
                        class="sidebar-link text-decoration-none waves-effect waves-dark sidebar-link text-decoration-none"
                        href="{{ route('users.index') }}" aria-expanded="false">
                        <i class="bi bi-people pr-2"></i>
                        <span class="hide-menu">Users</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a :active="request()->routeIs('movie.index')" class="sidebar-link text-decoration-none waves-effect waves-dark sidebar-link
                        text-decoration-none" href="{{ route('movie.index') }}" aria-expanded="false">
                        <i class="bi bi-camera-reels pr-2"></i>
                        <span class="hide-menu">Movie</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a :active="request()->routeIs('roles.index')" class="sidebar-link text-decoration-none waves-effect waves-dark sidebar-link
                                            text-decoration-none" href="{{ route('roles.index') }}"
                        aria-expanded="false">
                        <i class="bi bi-list-task pr-2"></i>
                        <span class="hide-menu">Role</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a :active="request()->routeIs('genre.index')" class="sidebar-link text-decoration-none waves-effect waves-dark sidebar-link
                                                            text-decoration-none" href="{{ route('genre.index') }}"
                        aria-expanded="false">
                        <i class="bi bi-bookmark pr-2"></i>
                        <span class="hide-menu">Genre</span>
                    </a>
                </li>


            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>

</aside>

resources/views/layouts/userNavigation.blade.php
<div class="container">
    <header class="blog-header lh-1 py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 pt-1">
            </div>
            <div class="col-4 text-center">
                <a class="blog-header-logo text-dark" href="#">MovieList</a>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
                <a class="link-secondary" href="#" aria-label="Search">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                        stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img"
                        viewBox="0 0 24 24">
                        <title>Search</title>
                        <circle cx="10.5" cy="10.5" r="7.5" />
                        <path d="M21 21l-5.2-5.2" />
                    </svg>
                </a>
                @if (Route::has('login'))
                @auth
                <a href="{{ url('/dashboard') }}" class="btn btn-sm btn-outline-secondary">Dashboard</a>
                @else
                <a href="{{ route('login') }}" class="px-2 text-decoration-none text-dark">Log in</a>

                @if (Route::has('register'))
                <a href="{{ route('register') }}" class="px-2 text-decoration-none text-dark">Register</a>
                @endif
                @endauth
                @endif
            </div>
        </div>
    </header>

    {{-- <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
            <a class="p-2 link-secondary" href="#">World</a>
            <a class="p-2 link-secondary" href="#">U.S.</a>
            <a class="p-2 link-secondary" href="#">Technology</a>
            <a class="p-2 link-secondary" href="#">Design</a>
            <a class="p-2 link-secondary" href="#">Culture</a>
            <a class="p-2 link-secondary" href="#">Business</a>
            <a class="p-2 link-secondary" href="#">Politics</a>
            <a class="p-2 link-secondary" href="#">Opinion</a>
            <a class="p-2 link-secondary" href="#">Science</a>
            <a class="p-2 link-secondary" href="#">Health</a>
            <a class="p-2 link-secondary" href="#">Style</a>
            <a class="p-2 link-secondary" href="#">Travel</a>
        </nav>
    </div> --}}
</div>